language: elixir
sudo: false

# Elixir versions
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.0
  - 1.3.2

# Erlang versions
otp_release:
  - 17.5
  - 18.1

env:
  - MIX_ENV=test

# Speed up the build
cache:
  directories:
    - deps
    - _build

# Need the file(1) command to build libmagic itself, and the bits necessary to
# build libmagic.
addons:
  apt:
    packages:
      - autoconf
      - automake
      - file
      - gcc
      - git
      - make
      - tree
